# Generated by Django 6.0.2 on 2026-02-09 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mijoz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
                ('age', models.PositiveIntegerField(default=0)),
                ('address', models.CharField(max_length=255)),
                ('market_name', models.CharField(max_length=155)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('phone_number2', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
